import { Question } from "@/types/game";

export const LEVEL_1_QUESTIONS: Question[] = [
    { id: "1-1", type: "CHOICE", level: 1, content: "1 + 1 = ?", options: ["1", "2", "3", "4"], correctAnswer: "2" },
    { id: "1-2", type: "CHOICE", level: 1, content: "2 + 2 = ?", options: ["2", "4", "6", "8"], correctAnswer: "4" },
    { id: "1-3", type: "CHOICE", level: 1, content: "3 + 1 = ?", options: ["2", "3", "4", "5"], correctAnswer: "4" },
    { id: "1-4", type: "CHOICE", level: 1, content: "5 - 1 = ?", options: ["3", "4", "5", "6"], correctAnswer: "4" },
    { id: "1-5", type: "CHOICE", level: 1, content: "2 + 3 = ?", options: ["4", "5", "6", "7"], correctAnswer: "5" },
    { id: "1-6", type: "CHOICE", level: 1, content: "4 - 2 = ?", options: ["1", "2", "3", "4"], correctAnswer: "2" },
    { id: "1-7", type: "CHOICE", level: 1, content: "1 + 4 = ?", options: ["3", "4", "5", "6"], correctAnswer: "5" },
    { id: "1-8", type: "CHOICE", level: 1, content: "3 - 2 = ?", options: ["0", "1", "2", "3"], correctAnswer: "1" },
    { id: "1-9", type: "CHOICE", level: 1, content: "6 + 1 = ?", options: ["5", "6", "7", "8"], correctAnswer: "7" },
    { id: "1-10", type: "CHOICE", level: 1, content: "5 - 3 = ?", options: ["1", "2", "3", "4"], correctAnswer: "2" },
    { id: "1-11", type: "CHOICE", level: 1, content: "2 + 1 = ?", options: ["2", "3", "4", "5"], correctAnswer: "3" },
    { id: "1-12", type: "CHOICE", level: 1, content: "4 + 4 = ?", options: ["6", "7", "8", "9"], correctAnswer: "8" },
    { id: "1-13", type: "CHOICE", level: 1, content: "7 - 2 = ?", options: ["4", "5", "6", "7"], correctAnswer: "5" },
    { id: "1-14", type: "CHOICE", level: 1, content: "1 + 0 = ?", options: ["0", "1", "2", "3"], correctAnswer: "1" },
    { id: "1-15", type: "CHOICE", level: 1, content: "8 - 4 = ?", options: ["3", "4", "5", "6"], correctAnswer: "4" },
    { id: "1-16", type: "CHOICE", level: 1, content: "2 + 5 = ?", options: ["6", "7", "8", "9"], correctAnswer: "7" },
    { id: "1-17", type: "CHOICE", level: 1, content: "3 + 3 = ?", options: ["5", "6", "7", "8"], correctAnswer: "6" },
    { id: "1-18", type: "CHOICE", level: 1, content: "9 - 1 = ?", options: ["7", "8", "9", "10"], correctAnswer: "8" },
    { id: "1-19", type: "CHOICE", level: 1, content: "4 - 4 = ?", options: ["0", "1", "2", "3"], correctAnswer: "0" },
    { id: "1-20", type: "CHOICE", level: 1, content: "5 + 5 = ?", options: ["8", "9", "10", "11"], correctAnswer: "10" },
    { id: "1-21", type: "CHOICE", level: 1, content: "6 - 0 = ?", options: ["5", "6", "7", "8"], correctAnswer: "6" },
    { id: "1-22", type: "CHOICE", level: 1, content: "1 + 8 = ?", options: ["7", "8", "9", "10"], correctAnswer: "9" },
    { id: "1-23", type: "CHOICE", level: 1, content: "10 - 5 = ?", options: ["4", "5", "6", "7"], correctAnswer: "5" },
    { id: "1-24", type: "CHOICE", level: 1, content: "2 + 6 = ?", options: ["7", "8", "9", "10"], correctAnswer: "8" },
    { id: "1-25", type: "CHOICE", level: 1, content: "7 + 3 = ?", options: ["8", "9", "10", "11"], correctAnswer: "10" },
    { id: "1-26", type: "CHOICE", level: 1, content: "5 + 0 = ?", options: ["4", "5", "6", "7"], correctAnswer: "5" },
    { id: "1-27", type: "CHOICE", level: 1, content: "9 - 4 = ?", options: ["4", "5", "6", "7"], correctAnswer: "5" },
    { id: "1-28", type: "CHOICE", level: 1, content: "2 + 7 = ?", options: ["8", "9", "10", "11"], correctAnswer: "9" },
    { id: "1-29", type: "CHOICE", level: 1, content: "8 + 1 = ?", options: ["7", "8", "9", "10"], correctAnswer: "9" },
    { id: "1-30", type: "CHOICE", level: 1, content: "4 - 3 = ?", options: ["0", "1", "2", "3"], correctAnswer: "1" },
];
